name: 'Upload to Modrinth'
description: 'Uploads files to Modrinth via Labrinth API'
author: 'RubixDev'
inputs:
  token:
    description: 'Token used to authenticate with Modrinth API. Use a repository secret for this'
    required: true
  file_path:
    description: 'The path to the file you want to upload'
    required: true
  name:
    description: 'The display name for this file'
    required: true
  version:
    description: 'The version number. Ideally will follow semantic versioning'
    required: true
  changelog:
    description: 'The changelog for this version'
    required: false
  relations:
    description: 'List of projects this file is related to and their relation type. Separate with "," (no quotes). Format: projectId:relationType - Valid relationTypes are: required, optional, incompatible and embedded'
    required: false
  game_versions:
    description: 'The game versions to select on this file. Separate with "," (no quotes)'
    required: true
  release_type:
    description: 'The type of this release. Allowed values: "alpha", "beta", "release"'
    required: false
  loaders:
    description: 'The mod loaders that this version supports. Separate with "," (no quotes)'
    required: true
  featured:
    description: 'Whether the version is featured or not'
    required: true
  project_id:
    description: 'Project ID to upload file to. You can get the ID from the sidebar on a project page under "Technical Information"'
    required: true
  staging:
    description: "Whether to use Modrinth's staging api"
    required: false
  new_project_body:
    description: 'A new body for the mod page'
    required: false
outputs:
  id:
    description: 'The ID of the file created'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-up-circle'
  color: 'orange'
